name: Build a GreenHub Project
on: 
  push: 
    branches: [ $default-branch ]
    
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm run dist
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          dist/*.exe