name: Publish
on:
  push:
    branches: ['main']

jobs:
  build:
    name: Deploy to itch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: set ITCH_GAME
        id: ITCH_GAME
        run: echo '::set-output name=ITCH_GAME::${{secrets.ITCH_GAME}}'

      - name: Deploy to itch
        if: ${{ ITCH_GAME != ''}}
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: browser
          ITCH_GAME: ${{ secrets.ITCH_GAME }}
          ITCH_USER: ${{ secrets.ITCH_USER }}
          PACKAGE: www
